        <div class="container">
         <div class="slick-carousel row WhyZenosysInner d-flex align-items-center align-items-center">
            <div>
                <div class="slide-content col-md-12 WhyZenosysInnerBox">
                    <img src="<?php echo base_url(); ?>assets/images/Data-science1.png" alt="" class="img-fluid">

                    <h6 class="TitleH6">Data Science</h6>
                    <p>The power of data to chart your path to success</p>
                </div>
                </div>
 <div>
                <div class="slide-content col-md-12 WhyZenosysInnerBox">
                    <img src="<?php echo base_url(); ?>assets/images/Machine-learning1.png" alt="" class="img-fluid">
                    <h6 class="TitleH6">Machine Learning</h6>
                    <p>Make room for the new-age self learning system</p>

                </div>
            </div>
                <div>
                <div class="slide-content col-md-12 WhyZenosysInnerBox">
                    <img src="<?php echo base_url(); ?>assets/images/Deep-learning1.png" alt="" class="img-fluid">

                    <h6 class="TitleH6">Deep Learning Technologies</h6>
                    <p>Technological transformation for unparalleled potential</p>

                </div>
                </div>
               <div>
                <div class="slide-content col-md-12 WhyZenosysInnerBox">
                    <img src="<?php echo base_url(); ?>assets/images/Ai1.png" alt="" class="img-fluid">

                    <h6 class="TitleH6">Artificial Intelligence</h6>
                    <p>Smart AI solutions for demanding projects and ideas</p>

                </div>
                </div>
                  <div>
                <div class="slide-content col-md-12 WhyZenosysInnerBox">
                    <img src="<?php echo base_url(); ?>assets/images/Predictive-analysis1.png" alt="" class="img-fluid">

                    <h6 class="TitleH6">Predictive Analytics</h6>
                    <p>The power to stay one step ahead and plan for the future</p>

                </div>
                </div>

            </div>


            <div class="row CustomeRows">
                <div class="col-md-8 WhyZenosysContent">

                    <h2 class="TitleH2">Data Science</h2>
   <p class="TitleP">As Machine Learning and Artificial Intelligence gradually take over the trend, Data Science is that one humongous field that has the most scope for increased profitability. Data science is basically the application of scientific methodologies, processes and algorithms to process and analyze data.</p>
                    <p class="TitleP">The team at Zenocraft comprises some of the brightest experts in the field, enabling us providing Data Science Consultation Services as well as Data Science Solutions that best suit the project’s Extract-Transform-Load Process and Machine Learning Models that can analyze dynamic and growing data. Find out how Data Science can empower your projects.</p>


                </div>
                 <div class="col-md-4 WhyZenosysContent">
                      <img src="<?php echo base_url(); ?>assets/images/data-science.png" class="img-fluid CommanImg GovernmentImg fullwidth fullwidth2 Retail Telecommunication" style="max-width:90%">
                 </div>
               
            </div>
<div class="row CustomeRows">
                <div class="col-md-6 WhyZenosysContent keyFeaturesContentul">
                  <ul>
                      <li><b>Mitigate risk and fraud : </b> Via statistical, network, path, and big data methodologies, data scientists enable
predictive fraud propensity models which makes it easier to detect unusual data and
hence, mitigating fraud and risk.</li>
                      <li><b>Deliver relevant products : </b> Finding markets that best fit your provision was a task that data science has simplified
up to a whole extent. Deliver the right product, at the right time, to the right audience.
Through data science, you can also develop products that match the customer needs.</li>
                      
                    </ul>
                </div>
                <div class="col-md-6 WhyZenosysContent keyFeaturesContentul">
                    <ul>
                      <li><b>Personalized customer experience : </b>Since the data that is studied is generated by consumer activities, it gives a lot of insight
into their behaviour at a granular level. This insight is raw material for sales and
marketing teams to tailor consumer experience and increase loyalty.</li>
                      
                    </ul>
                </div>
            </div>


        </div>
